services:
  imks-frontend:
    container_name: frontend-imks
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    develop:
      watch:
        - action: sync+restart
          path: ./imks/
          target: /app
          ignore:
            - node_modules/
    environment:
      - NODE_ENV=development
